---
title: "InsertingZerosBatData"
output: html_document
date: "2023-09-15"
---


```{r}
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(plotly)
library(hrbrthemes)
library(htmlwidgets)
library(viridis)
library(viridisLite)
library(cowplot)
library(ggplot2)
library(openair)
library(htmlwidgets)


## Import the processed data with site and plot type columns added by Jackson 
bats <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Data/Acoustics/Bat Acoustic Data/ROutputs/OverviewProcessedBatData_2023-09-15/EcoForestBats_ForInsertingZeroes.csv",   
                 col_types = cols(...1 = col_skip()))

dim(bats)
# 17930 15



getwd()
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/Documents/1. PhD_Main/GitHub_link/EcoForest/EF"


## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Data/Acoustics/Bat Acoustic Data/ROutputs"

file.name <- "InsertingZerosBatData"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today

```


## Format the dataset
```{r}
bats1 <- bats1 %>%  
  mutate(across(c(AUTO.ID., site, sitetype), factor))

```



Create a data object that is just the nights when bats were recorded for each detector
```{r}

bat_sitemap <- bats1 %>% select(site, sitetype, siteplot) %>% distinct() 

# Aggregate numnber of bat passes per siteplot per night 
bats_nights_sum <- bats1 %>% group_by(siteplot, DATE.12) %>% dplyr::summarize(batpass = sum(n()))
head(bats_nights_sum)
#   siteplot DATE.12    batpass
#   <fct>    <date>       <int>
# 1 EF11-CC  2023-06-06      14
# 2 EF11-CC  2023-06-07      17
# 3 EF11-CC  2023-06-08       5
# 4 EF11-CC  2023-06-09      17
# 5 EF11-CC  2023-06-10       3
# 6 EF11-CC  2023-06-11      33

bats_nights_sum1 <- left_join(bats_nights_sum, bat_sitemap)
summary(bats_nights_sum1)
summary(bats_nights_sum1$siteplot)

## Number of nights with bat passes for each siteplot 
# EF11-CC EF11-NN EF12-CC EF12-NN  EF2-CC  EF2-NN  EF3-CC  EF3-NN  EF4-CC  EF4-NN  EF5-CC  EF5-NN  EF6-CC  EF6-NN  EF7-CC 
#      24      35      21      29      10      26      12      15      30      30      30      31      24      28      21 
#  EF7-NN  EF8-CC  EF8-NN  EF9-CC  EF9-NN 
#      34      26      32      32      36 

#write.csv(bats_nights_sum1, "bat pass aggregated by night wout zeronights.csv")

batnights <- bats_nights_sum
batnights$active.night <- "TRUE"
head(batnights)

#   siteplot DATE.12    batpass active.night
#   <fct>    <date>       <int> <chr>       
# 1 EF11-CC  2023-06-06      14 TRUE        
# 2 EF11-CC  2023-06-07      17 TRUE        
# 3 EF11-CC  2023-06-08       5 TRUE        
# 4 EF11-CC  2023-06-09      17 TRUE        
# 5 EF11-CC  2023-06-10       3 TRUE        
# 6 EF11-CC  2023-06-11      33 TRUE  

## Look for holes in the recording period: 

```


```{r}
# Use this plot as a map for detecting the sites that need checking
library(plotly)
library(hrbrthemes)
hrbrthemes::import_roboto_condensed()

#
 ggplot(batnights, aes(x=DATE.12, y=siteplot, fill=batpass)) +  geom_tile()
 
 # Need to NOT include the 16 observations with totally off dates. 
 
 t <- batnights %>% filter(DATE.12 > "2023-05-01") # lost 5 nights 
 ggplot(t, aes(x=DATE.12, y=siteplot, fill=batpass)) +  geom_tile()
 # Lots of gaps here! I imagine most are true zeroes, but we still need to check. 
 # Noticve how EF4-CC and EF3-CC have a huge gap in July 
 
 # It easier to create an interactive version of this map and I highly recommend doing this one site a time as well (makes your eyes cross less)
 
 #TEST  <- temp2 %>% filter(Site == c("P14", "C14", "MetA", "MetB")) %>% mutate(night = as.Date(night))

#test <- TEST  %>% 
#  mutate(text = paste0("Night: ", night , "\n", "Site: ", Site))


p <- ggplot(t, aes(x = DATE.12, y = siteplot, fill = batpass)) +
          geom_tile() +
           theme_ipsum()

pp <- ggplotly(p)
pp

htmlwidgets::saveWidget(as_widget(pp), file.path(output_today, "index_EF_NightCheck.html")) 

pEF9 <- t %>% filter(siteplot %in% c("EF9-NN", "EF9-CC")) %>% droplevels() %>% 
  ggplot(aes(x = DATE.12, y = siteplot, fill = batpass)) +
          geom_tile() +
           theme_ipsum()

ppef9 <- ggplotly(pEF9)
ppef9 

htmlwidgets::saveWidget(as_widget(pp), file.path(output_today,"index_EF9_NightCheck.html"))


# write.csv(t, file = file.path(output_today, "EF_NightCheck_unedited.csv")) # keep a back up for editing 
# write.csv(t, file = file.path(output_today, "EF_NightCheck_formanualedit.csv")) # and another for manually editing (or if you want to do this in R - please do!!) Maybe Emma and Jackson can do 5 sites each? 

# USE THIS CSV TO MANUALLY INSERT NIGHTS WHEN THE DETECTORS WERE WORKING AND DEPLOYED BUT NO DATA WAS COLLECTED THE WHOLE NIGHT! 

```



## Example code from a previous project - you will need to adapt this to your own data. 
## Let me know when you get to this point and get confused / i realize it isn't easy for you to interpret scripts from a project you did not work on! 
################################################
# Insert zero activity nights
################################################

```{r}
# dat <- bats
# summary(dat)
#---- ADDING MISSING HOURS

# First, adjust dataset to include nights when detectors were active but no data was collected. 

# POST MANUAL EDITING IN EXCEL! - see bottom code chunk for more info on how this csv file was built. 

# newnights <- Marker_night_inventory_0704_2022_edit <- read_delim("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/2. Marker 2019-2020/Marker 2022/Datasets/Marker_night_inventory_0704.2022_edit.csv", 
#     delim = ";", escape_double = FALSE, trim_ws = TRUE) # 951 obs of 3 vars 
#   
#   
# newnights1 <- newnights  %>%  mutate(night = as.Date(night, "%d.%m.%Y")) %>%  arrange(Site, night) %>% mutate(active.night = as.factor(active.night), Site = as.factor(Site))
# str(newnights1)
# summary(newnights1$Site)
# 
# active.nights<- newnights1 %>% dplyr::select(Site, night) %>% unique() #951 nights all together
# active.nights$active.night<-TRUE
# # Use existing dataset hours to create nighthour column for now. 
# hours<-seq(min(dat$nighthour),max(dat$nighthour),3600) #--full daily sequence of hours for the entire study period
# hours<-hours[as.numeric(format(hours,"%H"))%in%sort(unique(as.numeric(format(dat$nighthour,"%H"))))]#--restrict to "nighthours" found in the data
# 
# temp<-expand.grid(Site=unique(dat$Site),  nighthour=hours, guild = unique(dat$guild), behavior = unique(dat$behavior)) #----expanded data, 257664 obs of 4 vars 
# temp$night <-  as.POSIXct(format(temp$nighthour,"%Y-%m-%d"),tz="UTC")
# 
# temp2<-merge(temp,active.nights)
# dim(temp2) # 170400 obs of 6 vars 
# 
# temp3<-merge(temp2,dat,all.x=TRUE)
# dim(temp3) # 170400 obs of 25 vars 
# summary(temp3) # 165238 (previously 165224) NA obs 
# 
# # temp2<-merge(temp, active.nights) # 811 obs of 3 variables 
# 
# summary(temp2$Site) # number of monitoring nights per site 
# # Met45 Met95   N02   N04   N08   N09   N10   N11   N14   P02   P04   P08   P09   P10   P11   P14 
#    70    70    59    44    60    48    60    60    60    60    60    60    60    60    60    60 
```

