---
title: "Spatial Data EcoForest"
output: html_document
---

#Work environment 
```{r}
library(tidyverse)
library(dplyr)
library(raster)
library(rgdal)
library(rgeos)
library(mapview)
library(sf)
library(sp)
library(maps)
library(leaflet)
library(randomcoloR)
library(wesanderson)
library(leaflegend)
library(osmdata)
library(MetBrewer)
library(colorBlindness)
library(colorblindcheck)
library(ggmap)
library(maptools)
library(spatstat)

output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Location Data/DigitalPoints"

## 
 file.name <- "MainSites"
# 
 todays_date <- Sys.Date()
# 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
 dir.name
# 
 dir.create(dir.name) 
 # "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Location Data/DigitalPoints/MainSites_2023-05-31"

output_today <- dir.name
output_today

setwd(output_today)
getwd()


# Turbine locations
tpt<- read.csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Location Data/Sites_31052023.csv", sep = ";")
names(tpt)

tpt1 <- tpt

# Factorize useful columns 
tpt1$Lokalitet = as.factor(tpt1$Lokalitet)
tpt1$Site = as.factor(tpt1$Site)
tpt1$Kategori = as.factor(tpt1$Kategori)

# Example code for how to make another category based on existing factor levels
# tpt1 <- tpt %>% mutate(Monitoring = case_when(
#    Name %in% c("T-02", "T-04", "T-09", "T-10",  "T-14") ~ "AcousticsOnly",
#    Name %in% c("T-01", "T-03", "T-05", "T-06", "T-07", "T-12", "T-13", "T-15") ~ "Not Monitored", 
#    Name %in% c("T-08", "T-11") ~ "AcousticsAndCT") )

# tpt1$Monitoring = as.factor(tpt1$Monitoring)



```

# Convert lat long columns to spatial objects, export 
More info on geo projections in R
http://companion.soep.de/Working%20with%20SOEP%20Data/Working%20with%20spatial%20data%20in%20R.html

```{r}
tpt1 <- tpt %>% rename ("Lat" = "Coordinate.X0Y0..Lat.",  "Lon" = "Coordinate.X0Y0..Lon." )
tpt2 <- st_as_sf(tpt1,coords=c("Lon", "Lat"),crs = "+proj=latlong +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
crs(tpt2$geometry)
str(tpt2) # sf dataframe 

# Check that these can be plotted 
plot(tpt2[1])

# Formal calss SpatialPointsDataFrame
df <- SpatialPointsDataFrame(coords=tpt1[,c(8, 7)],data=tpt1, proj4string = CRS("+init=epsg:4326")) 
crs(df) # WGS84
plot(df)

# Create UTM columns 
dfutm <- spTransform(df, CRS("+proj=utm +zone=32")) 
st_crs(dfutm)
plot(dfutm)

dfsp <- as(dfutm, "Spatial") 
class(dfsp)

dfsf <- as(dfutm, "sf") 
class(dfsf)



getwd()
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Location Data/DigitalPoints/MainSites_2023-05-31"
st_write(dfsf,"EcoForestSitePlots.gpkg")

# Export shape file
writeOGR(dfutm, dsn= "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Location Data/DigitalPoints/MainSites_2023-05-31",
     dataset_options="GPX_USE_EXTENSIONS=yes",layer="ESRIS Shapefile",driver="GPX", overwrite_layer = T)

writeOGR(dfutm, dsn= "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Location Data/DigitalPoints/MainSites_2023-05-31/waypoints.gpx",
     dataset_options="GPX_USE_EXTENSIONS=yes",layer="waypoints",driver="GPX", overwrite_layer = T) 



```
*Back up option*
Code / functions from : 
https://stackoverflow.com/questions/18639967/converting-latitude-and-longitude-points-to-utm


# Site Map 
```{r}

plot1 <- tpt2 %>% leaflet() %>% 
   addTiles() %>%
   addCircleMarkers(radius = 7, color = "gray",
                       fillOpacity = 0.5,  stroke = TRUE) %>% 
  addScaleBar(position = "bottomright")
plot1$x$options = append(plot1$x$options, list("zoomControl" = FALSE,  "scaleBar"=TRUE))
plot1 

###############################################

plot1 <- df %>% leaflet() %>% 
   addTiles() %>%
   addCircleMarkers(radius = 7, color = "gray",
                       fillOpacity = 0.5,  stroke = TRUE) %>% 
  addScaleBar(position = "bottomright")
plot1$x$options = append(plot1$x$options, list("zoomControl" = FALSE,  "scaleBar"=TRUE))
plot1 

```
