---
title: "Overview bird data"
output: html_document
date: "2023-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Goals 

- Read in all raw bird recordings collected in the summer of 2023 for the EcoForest project
- Add metadata columns based on filenames and filepaths 
- Send to Jackson 


```{r}
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)

getwd()
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/Documents/1. PhD_Main/GitHub_link/EcoForest/EF"

## Setup output directory 
output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Data/Acoustics/Bird Acoustic Data/Outputs"

file.name <- "ExportingBirdAcousticData"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today

```

# Read all bird files 
```{r}
# All raw and processed bat data located here 
# inputEF <-"P:/EcoForest/Acoustics" # First do a practice run to see if a combination of patterns can be used

# This will select the file path of all files that begin with S4A (bird acoustic data) 
# Will need to filter out non - .wav files in the next step. 

# This is going to take an eternity.

# my_files <- list.files(path = inputEF, pattern= "S4A", recursive = TRUE) 
# beep()
# 
# head(my_files)
# 
# my_df <- as.data.frame(my_files)
# dim(my_df)
# # [1] 18249     1
# 
# ## Remove any files that do not end in .wav 
# 
# my_df1 <- my_df %>% filter(str_detect(my_files, ".wav"))
# dim(my_df1)
# [1] 18157     1

#write.csv(my_df1, file = file.path(output_today, "RawBirdData_allfilepaths.csv"))
# 24.10.2023

## Read in "RawBirdData_allfilepaths.csv" here 

birds <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/5. EcoForest/Data/Acoustics/Bat Acoustic Data/ROutputs/ExportingBirdAcousticData_2023-10-24/RawBirdData_allfilepaths.csv", 
     col_types = cols(...1 = col_skip()))

```

## Make metadata columns from file paths 
```{r}
head(birds)
#EF11-CC-A/DATA/19.07.2023_EF11-CC-A/Data/S4A16276_20230626_140601.wav



# Feel free to use different terminology, this is just an easy solution for me but Jackson and Emma are free to use the syntax that works for them so long as it is clear and consistent. 
incols <- c("SitePlot", "DATA", "Collection", "Data", "filename")

birds1 <- birds %>% 
  tidyr::separate(col = my_files,
                                        sep = "/",
                                       into = incols, 
                                       remove = FALSE)

birds2 <- birds1 %>% select(-c(DATA, Data)) 

head(birds2$SitePlot)
# [1] "EF11-CC-A" "EF11-CC-A" "EF11-CC-A" "EF11-CC-A" "EF11-CC-A" "EF11-CC-A"

incols <- c("Site", "PlotType", "Avian")

birds3 <- birds2 %>% 
  tidyr::separate(col = SitePlot,
                                        sep = "-",
                                       into = incols, 
                                       remove = FALSE)
# A bit more tidying 
birds3 <- birds3 %>% 
  rename(filepath = my_files) %>% 
  select(-Avian) %>% 
  mutate(SitePlot = factor(SitePlot)) %>% 
  mutate(Site = factor(Site)) %>% 
  mutate(PlotType = factor(PlotType)) 
  
summary(birds3$SitePlot) 
# EF11-CC-A EF11-NN-A EF12-CC-A EF12-NN-A  EF2-CC-A  EF2-NN-A  EF3-CC-A  EF3-NN-A  EF4-CC-A  EF4-NN-A 
#       941       940       924       924       925       922       921       926       939       938 
#  EF5-CC-A  EF5-NN-A  EF6-CC-A  EF6-NN-A  EF7-CC-A  EF7-NN-A  EF8-CC-A  EF8-NN-A  EF9-CC-A  EF9-NN-A 
#       896       898       942       941       937       934       937       495       940       937 

summary(birds3$Site) 
# EF11 EF12  EF2  EF3  EF4  EF5  EF6  EF7  EF8  EF9 
# 1881 1848 1847 1847 1877 1794 1883 1871 1432 1877 

summary(birds3$PlotType) 
#   CC   NN 
# 9302 8855 

## Check for duplicates 

test <- unique(birds3$filename)
# 18137 unique elements 
# There are 18157 observations in birds3, so there are 20 duplicates somewhere. Lets find out where. 

test_df <- as.data.frame(birds3$filename)
test_df$filename <- test_df[,1]

dups <- test_df [duplicated(test_df$filename),]

dups_meta <- left_join(dups, birds3)

test1 <- unique(dups_meta$filename)
head(test1)
test2_df <- as.data.frame(test1)

# There are 20 recordings from EF2-CC-A that were backed up twice under two different collections. 
# The true collection for these recordings would have been "28.06" because the recordings are from before this date. 

# Were there actual recordings collected from EF2-CC-A on 21.07.2023? Have these been lost in the backup process (human error, most likely me (Reed) 

##

ef2cca <- birds3 %>% filter(SitePlot == "EF2-CC-A") %>% 
  droplevels() %>% 
  mutate(Collection = factor(Collection)) # 925 obs
ef2cca

incols <- c("detector", "date", "time.wav")

ef2cca <- ef2cca %>% 
  tidyr::separate(col = filename,
                                        sep = "_",
                                       into = incols, 
                                       remove = FALSE)
library(lubridate)
ef2cca$Date <- ymd(ef2cca$date)

ggplot(ef2cca) + geom_bar(aes(x = Date, y = after_stat(count), fill = Collection), position = "stack") 

# These files were simply backed up twice, once in each collection folder, so I can delete them from the 21.07.2023 collection folder and this should be alright. 

dups_meta_sub <- dups_meta %>% filter(Collection == "21.07.2023_EF2-CC-A") %>% droplevels()

birds4 <- anti_join(birds3, dups_meta_sub) # 8137, lost the 20 duplicate observations in the incorrect collection folder. Nice!

#write.csv(birds4, file = file.path(output_today, "Overview_birdata_duplicates_removed.csv"))

# Now also remove these duplicate files from in the folder. 
# dups_meta_sub$fullfilepath <- paste0("P:/EcoForest/Acoustics/", dups_meta_sub$filepath)
# 
# deletethis <- dups_meta_sub$fullfilepath 
# 
# file.remove(deletethis) # done 

```


```{r}
summary(birds4$PlotType)
#   CC   NN
# 9282 8855

summary(birds4$SitePlot)
# EF11-CC-A EF11-NN-A EF12-CC-A EF12-NN-A  EF2-CC-A  EF2-NN-A  EF3-CC-A  EF3-NN-A  EF4-CC-A  EF4-NN-A  EF5-CC-A 
#       941       940       924       924       905       922       921       926       939       938       896 
#  EF5-NN-A  EF6-CC-A  EF6-NN-A  EF7-CC-A  EF7-NN-A  EF8-CC-A  EF8-NN-A  EF9-CC-A  EF9-NN-A 
#       898       942       941       937       934       937       495       940       937

# 18137 ten minute recordings 

# Manual listening - 20 minutes of recording per SitePlot
# 400/60
# 6.7 hours of recordings to go through 

incols <- c("detector", "date", "time.wav")

birds5 <- birds4 %>% 
  tidyr::separate(col = filename,
                                        sep = "_",
                                       into = incols, 
                                       remove = FALSE)
birds5$Date <- ymd(birds5$date)

summary(birds5$Date)
#         Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
# "2023-06-05" "2023-06-20" "2023-06-30" "2023-06-30" "2023-07-10" "2023-07-23
```

