---
title: "PostManualID_Combine_and_Clean_csvs"
output: html_document
date: "2025-12-09"
---


# Prepare workspace and import data 
```{r Libraries}
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(ggdark)
library(RColorBrewer)
library(cowplot)
library(readxl)
library(writexl)
library(suncalc)


output <-"P:/EcoForest/ProcessedAcoustics/ROutputs" # where you want to save your data

file.name <- "PostManualID_Combine_and_Clean_csvs"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today
# "P:/EcoForest/ProcessedAcoustics/ROutputs/PostManualID_Combine_and_Clean_csvs_2025-12-09"

```


```{r}
# Make csvs into lists
EF_2CB <-read_csv("P:/EcoForest/Acoustics/EF2-CC-B/ID/id.csv")
dim(EF_2CB)
#177  44
EF_2CB$Site <- "EF02-CC"
EF_2CB$SiteType <- "Clear cut"
EF_2CB$SitePair <- "EF02"
names(EF_2CB)

EF_2NB <-read_csv("P:/EcoForest/Acoustics/EF2-NN-B/ID/id.csv")
dim(EF_2NB)
#629  44
EF_2NB$Site <- "EF02-NN"
EF_2NB$SiteType <- "Near natural"
EF_2NB$SitePair <- "EF02"
names(EF_2NB)

EF_3CB <-read_csv("P:/EcoForest/Acoustics/EF3-CC-B/ID/id.csv") 
dim(EF_3CB)
# 187  44 
EF_3CB$Site <- "EF03-CC"
EF_3CB$SiteType <- "Clear cut"
EF_3CB$SitePair <- "EF03"
names(EF_3CB)

EF_3NB <-read_csv("P:/EcoForest/Acoustics/EF3-NN-B/ID/id.csv")
dim(EF_3NB)
#286  44
EF_3NB$Site <- "EF03-NN"
EF_3NB$SiteType <- "Near natural"
EF_3NB$SitePair <- "EF03"
names(EF_3NB)

EF_4CB <-read_csv("P:/EcoForest/Acoustics/EF4-CC-B/ID/id.csv") 
dim(EF_4CB)
#2975   44
EF_4CB$Site <- "EF04-CC"
EF_4CB$SiteType <- "Clear cut"
EF_4CB$SitePair <- "EF04"
names(EF_4CB)

EF_4NB <-read_csv("P:/EcoForest/Acoustics/EF4-NN-B/ID/id.csv") 
dim(EF_4NB)
#1583   44
EF_4NB$Site <- "EF04-NN"
EF_4NB$SiteType <- "Near natural"
EF_4NB$SitePair <- "EF04"
names(EF_4NB)

EF_5CB <-read_csv("P:/EcoForest/Acoustics/EF5-CC-B/ID/id.csv" )
dim(EF_5CB)
#598   44
EF_5CB$Site <- "EF05-CC"
EF_5CB$SiteType <- "Clear cut"
EF_5CB$SitePair <- "EF05"
names(EF_5CB)

EF_5NB <-read_csv("P:/EcoForest/Acoustics/EF5-NN-B/ID/id.csv" )
dim(EF_5NB)
#947   44
EF_5NB$Site <- "EF05-NN"
EF_5NB$SiteType <- "Near natural"
EF_5NB$SitePair <- "EF05"
names(EF_5NB)

EF_6CB <-read_csv("P:/EcoForest/Acoustics/EF6-CC-B/ID/id.csv")
dim(EF_6CB)
#369  44
EF_6CB$Site <- "EF06-CB"
EF_6CB$SiteType <- "Clear cut"
EF_6CB$SitePair <- "EF06"
names(EF_6CB)

EF_6NB <-read_csv("P:/EcoForest/Acoustics/EF6-NN-B/ID/id.csv" )
dim(EF_6NB)
#2062      44
EF_6NB$Site <- "EF06-NN"
EF_6NB$SiteType <- "Near natural"
EF_6NB$SitePair <- "EF06"
names(EF_6NB)

EF_7CB <-read_csv("P:/EcoForest/Acoustics/EF7-CC-B/ID/id.csv")
dim(EF_7CB)
#436  44
EF_7CB$Site <- "EF07-CB"
EF_7CB$SiteType <- "Clear cut"
EF_7CB$SitePair <- "EF07"
names(EF_7CB)

EF_7NB <-read_csv("P:/EcoForest/Acoustics/EF7-NN-B/ID/id.csv" )
dim(EF_7NB)
#1247      44
EF_7NB$Site <- "EF07-NN"
EF_7NB$SiteType <- "Near natural"
EF_7NB$SitePair <- "EF07"
names(EF_7NB)

EF_8CB <-read_csv("P:/EcoForest/Acoustics/EF8-CC-B/ID/id.csv" )
dim(EF_8CB)
#878  44
EF_8CB$Site <- "EF08-CB"
EF_8CB$SiteType <- "Clear cut"
EF_8CB$SitePair <- "EF08"
names(EF_8CB)

EF_8NB <-read_csv("P:/EcoForest/Acoustics/EF8-NN-B/ID/id.csv")
dim(EF_8NB)
#3235   44
EF_8NB$Site <- "EF08-NN"
EF_8NB$SiteType <- "Near natural"
EF_8NB$SitePair <- "EF08"
names(EF_8NB)

EF_9CB <-read_csv("P:/EcoForest/Acoustics/EF9-CC-B/ID/id.csv" )
dim(EF_9CB)
#4788  44
EF_9CB$Site <- "EF09-CB"
EF_9CB$SiteType <- "Clear cut"
EF_9CB$SitePair <- "EF09"
names(EF_9CB)

EF_9NB <-read_csv("P:/EcoForest/Acoustics/EF9-NN-B/ID/id.csv" )
dim(EF_9NB)
#7194  44
EF_9NB$Site <- "EF09-NN"
EF_9NB$SiteType <- "Near natural"
EF_9NB$SitePair <- "EF09"
names(EF_9NB)

EF_11CB <-read_csv("P:/EcoForest/Acoustics/EF11-CC-B/ID/id.csv")
dim(EF_11CB)
#571  44
EF_11CB$Site <- "EF11-CB"
EF_11CB$SiteType <- "Clear cut"
EF_11CB$SitePair <- "EF11"
names(EF_11CB)

EF_11NB <- read_csv("P:/EcoForest/Acoustics/EF11-NN-B/ID/id.csv" )
dim(EF_11NB)
#4891  44
EF_11NB$Site <- "EF11-NN"
EF_11NB$SiteType <- "Near natural"
EF_11NB$SitePair <- "EF11"
names(EF_11NB)

EF_12CB <-read_csv("P:/EcoForest/Acoustics/EF12-CC-B/ID/id.csv" )
dim(EF_12CB)
#6113  44
EF_12CB$Site <- "EF12-CB"
EF_12CB$SiteType <- "Clear cut"
EF_12CB$SitePair <- "EF12"
names(EF_12CB)

EF_12NB <-read_csv("P:/EcoForest/Acoustics/EF12-NN-B/ID/id.csv" )
dim(EF_12NB)
#2588   44
EF_12NB$Site <- "EF12-NN"
EF_12NB$SiteType <- "Near natural"
EF_12NB$SitePair <- "EF12"
names(EF_12NB)

### Now combine all together
combined <- rbind(EF_2CB, EF_2NB, EF_3CB, EF_3NB,
                  EF_4CB, EF_4NB, EF_5CB, EF_5NB,
                  EF_6CB, EF_6NB, EF_7CB, EF_7NB,
                  EF_8CB, EF_8NB, EF_9CB, EF_9NB,
                  EF_11CB, EF_11NB, EF_12CB, EF_12NB)

combined$autoid <- factor(combined$`AUTO ID`)
combined$manualid <- factor(combined$`MANUAL ID*`)
#41754 observations of 47 vars

summary(combined)

## Check that these combined alright

DF <- combined %>% 
  dplyr::mutate(Site = factor(Site), 
                SiteType = factor(SiteType), 
                SitePair = factor(SitePair)) %>% 
  dplyr::select(-c(`AUTO ID`, `MANUAL ID*`)) %>% droplevels()

summary(DF)
summary(DF$autoid)
# BARBAR EPTNIL MYOBRA MYODAU MYOMYS MYONAT   NoID  Noise NYCNOC PIPPYG PLEAUR VESMUR 
#    194   4093    791   3101   2085     55   7101  23824     76     29    286    119
summary(DF$manualid)
summary(DF$Site)
# EF02-CC EF02-NN EF03-CC EF03-NN EF04-CC EF04-NN EF05-CC EF05-NN 
#     177     629     187     286    2975    1583     598     947 
# EF06-CB EF06-NN EF07-CB EF07-NN EF08-CB EF08-NN EF09-CB EF09-NN 
#     369    2062     436    1247     878    3235    4788    7194 
# EF11-CB EF11-NN EF12-CB EF12-NN 
#     571    4891    6113    2588 

summary(DF$SiteType)
   # Clear cut Near natural 
   #     17092        24662 

# Identifying noise
# Make all observations that where autoID=Noise into manualid = Noise

## First check if all NAs are Noise

checkthis <- DF %>% filter(is.na(manualid)) %>% droplevels()
summary(checkthis$autoid)
#Only noise, good 
# 23786 autoid Noise recordings in total 

#Clean the Noise category for manualids  
DF1 <- DF %>% mutate(manualid = factor(case_when(
                                      autoid == "Noise" ~ "Noise",
                                      manualid == "NOISE" ~ "Noise", 
                                      manualid == "SHREW" ~ "Noise", 
                                      manualid == "SHREW?" ~ "Noise", 
                                      manualid == "SMALL MAMMAL" ~ "Noise", 
                                      TRUE ~ manualid)))

summary(DF1$manualid)
# 24024 Noise recordings 
#export as if before doing any further modifications 

summary(DF1$DATE)

#write.csv(DF1, file=file.path(output, "EcoForest_FullManual_combinedID.csv"))
#output_today
#  "P:/EcoForest/ProcessedAcoustics/ROutputs/PostManualID_Combine_and_Clean_csvs_2025-12-09"

```



next step: 
1. all data compiled
      - add red list category?
2. aggregate by night
3. inserting zeroes
4. data exploration


## Cleaning manual.ids 
```{r Cleaning}

#Now drop noise recordings and clean the manual ids 

DF2 <- DF1 %>% filter(manualid != "Noise")
dim(DF2)
# 17730    47 
# The number of recordings that have bat passes, before parsing 

## When you drop the noise recordings, you also lose the files with date errors. 
summary(DF2$DATE)

## Check for duplicate files 
duplicates <- DF2 %>%
  group_by(`IN FILE`) %>%
  filter(n() > 1) %>% 
  ungroup()
# No duplicates, good. 


# Trim down to just essential columns
DF3 <- DF2 %>% 
  dplyr::select(`IN FILE`, INDIR, OUTDIR, DURATION, 
         DATE, TIME, HOUR, 
         `DATE-12`, `TIME-12`, `HOUR-12`, 
         autoid, manualid, 
         Site, SiteType, SitePair) %>% 
  rename(filename =`IN FILE`, 
         DATE.12 = `DATE-12`, 
         TIME.12 = `TIME-12`, 
         HOUR.12 = `HOUR-12`) 
#17730 obs of 15 variables 

summary(DF3)
summary(DF3$manualid)
## Clean any inconsistencies in the manual ids for different taxa 

DF3$mid <- factor(gsub("MYSP", "MYOT", DF3$manualid))
DF3$mid <- factor(gsub("\\.T", ".S", DF3$mid)) # There was only one PPYG.T
DF3$mid <- factor(gsub("PIPYG", "PPYG", DF3$mid))
summary(DF3$mid)
```



```{r Parse behavior and multiple species}
# Split recordings with multiple species into separate rows
dim(DF3)
# 17730    16
DF4 <- DF3 %>% separate_rows(mid, sep = "_")
DF4$mid <- factor(DF4$mid)
summary(DF4$mid)
# 
#     ENIL   ENIL.B ENIL.B.S   ENIL.S     EPNI     MYOT 
#     4170      685        9       48        1    10124 
#   MYOT.B MYOT.B.S   MYOT.S     NNOC   NNOC.B     NoID 
#     2366        2        9       11        2       33 
#   NoID.S     NYCT   NYCT.B NYCT.B.S   NYCT.S     PAUR 
#       16      188       27        1      105      114 
#   PAUR.S   PISP.S     PPYG   PPYG.B   PPYG.S 
#       77        1       28        4        1 
dim(DF4)
# 18022    16

#18022-17730
# 292 observations where there were multiple bats in a pass. 

# Create separate behavior column, remove behavior tags from manuals ids
DF5 <- DF4 %>%
  mutate(mid1 = as.character(mid)) %>% 
  mutate(behavior = factor(case_when(
    str_detect(mid1, ".B") ~ "Feeding",
    str_detect(mid1, ".S") ~ "Social",
    str_detect(mid1,".B.S") ~ "Feeding",
    TRUE ~ "Commuting"
  ))) %>% 
  mutate(mid1 = factor(mid1)) 

summary(DF5$behavior)
# Commuting   Feeding    Social 
#     14669      3096       257 

summary(DF5$mid1)

# Removing behavior from manual ID column
DF5$mid <- factor(gsub(".B", "", DF5$mid))
DF5$mid <- factor(gsub(".S", "", DF5$mid))
summary(DF5$mid)
 # ENIL  EPNI  MYOT  NNOC  NoID  NYCT  PAUR    PP  PPYG 
 # 4912     1 12501    13    49   321   191     1    33 

## Now fix the EPNI and PP (should be PISP)
DF5$mid <- factor(gsub("EPNI", "ENIL", DF5$mid))
DF5$mid <- factor(gsub("PP", "PISP", DF5$mid))
DF5$mid <- factor(gsub("PISPYG", "PPYG", DF5$mid))
summary(DF5$mid)
 # ENIL  MYOT  NNOC  NoID  NYCT  PAUR  PISP  PPYG 
 # 4913 12501    13    49   321   191     1    33 

# Clean the Manual id columns 
DF6 <- DF5 %>% mutate(manualid = factor(mid)) %>% 
  dplyr::select(-c(mid, mid1)) 

summary(DF6)

#write.csv(DF6, file = file.path(output_today, "BatPasses_NoNoise_Cleaned_Behavior.csv"))
# 09.12.2026


### Add a bat taxa column 
summary(DF6$manualid)
# "ENIL" "MYOT" "NNOC" "NoID" "NYCT" "PAUR" "PISP" "PPYG"

bats1 <- DF6 %>% mutate(taxa = factor(case_when(
  manualid == "ENIL" ~ "Eptesicus nilssonii",
  manualid == "MYOT" ~ "Myotis spp.",
  manualid == "NNOC"~ "Nyctalus noctula",
  manualid == "NYCT"~ "Nyctaloid",
  manualid == "PISP" ~ "Pipistrellus spp.",
  manualid == "PPYG" ~ "Pipistrellus pygmaeus",
  manualid == "PAUR" ~ "Plecotus auritus", 
  manualid == "NoID" ~ "Unknown bat"
))) 

dim(bats1)
# 18022    17

levels(bats1$Site) ## something strange happened with the site names... 
bats1$Site <- factor(gsub("-CB", "-CC", bats1$Site))
levels(bats1$Site) # That fixed it 

## Good, export 
#write.csv(bats1, file = file.path(output_today, "BatPassesCombined_NoNoise_Tidied.csv"))
# 11.12.2025

```


## Aggregate to night



### Zero nights
```{r}

## Start nu accounting for nights when detectors were deployed but no data was collected (zero nights) 
active.nights <- read_xlsx("~/1. PhD_Main/GitHub_link/EcoForest/Data wrangling Emma/3. Aggregating by night and inserting zeroes/Input/BatPassActiveNights.xlsx")
## 807 of 6 
### This needs to not have any bat pass information in it. That data you need to get from the bats1 object - this is why you got so much more bat passes in the end. 

active.nights <- active.nights %>% select(-batpass)

active.nights$SITEPLOT <- factor(active.nights$SITEPLOT)

sitenights <- active.nights %>%
  group_by(SITEPLOT) %>%
  dplyr::summarize(
    min_date = min(as.Date(DATE.12)),
    max_date = max(as.Date(DATE.12))
  )

#    SITEPLOT  min_date   max_date  
#    <fct>     <date>     <date>    
#  1 EF11-CC-B 2023-06-06 2023-07-18
#  2 EF11-NN-B 2023-06-06 2023-07-18
#  3 EF12-CC-B 2023-06-08 2023-06-27
#  4 EF12-NN-B 2023-06-08 2023-07-19
#  5 EF2-CC-B  2023-06-09 2023-07-07
#  6 EF2-NN-B  2023-06-09 2023-07-20
#  7 EF3-CC-B  2023-06-11 2023-07-21
#  8 EF3-NN-B  2023-06-11 2023-07-21
#  9 EF4-CC-B  2023-06-11 2023-07-22
# 10 EF4-NN-B  2023-06-11 2023-07-22
# 11 EF5-CC-B  2023-06-12 2023-07-22
# 12 EF5-NN-B  2023-06-12 2023-07-22
# 13 EF6-CC-B  2023-06-10 2023-07-21
# 14 EF6-NN-B  2023-06-10 2023-07-21
# 15 EF7-CC-B  2023-06-09 2023-07-20
# 16 EF7-NN-B  2023-06-09 2023-07-20
# 17 EF8-CC-B  2023-06-05 2023-07-17
# 18 EF8-NN-B  2023-06-05 2023-07-17
# 19 EF9-CC-B  2023-06-07 2023-07-19
# 20 EF9-NN-B  2023-06-07 2023-07-19

## I have checked these dates against the maintenance forms. Now I will insert missing nights. 

# Ensure your date column is Date type
# active.nights <- active.nights %>% mutate(DATE.12 = as.Date(DATE.12))
# 
# # Fill in missing dates
# active.nights_true<- active.nights %>%
#   group_by(SITEPLOT) %>%
#   complete(DATE.12 = seq(min(DATE.12), max(DATE.12), by = "day")) %>%
#   ungroup()
## Same number of variables, so it was already correct. Nice. 


```



## Aggregate bat passes to night per site
- Insert zeros
- merge with night aggregated weather data 
```{r}
# Format the date columns 
bats1 <- bats1 %>% mutate(date = as.Date(DATE),
                           night = as.Date(DATE.12))

## Note that you have 18022 rows here which you should have 18022 bat passes in your aggregated dataset as well. 

bat_sitemap <- bats1 %>% dplyr::select(c(Site, SiteType, SitePair)) %>% distinct() 
head(bat_sitemap)
#   Site    SiteType     SitePair
#   <fct>   <fct>        <fct>   
# 1 EF02-CC Clear cut    EF02    
# 2 EF02-NN Near natural EF02    
# 3 EF03-CC Clear cut    EF03    
# 4 EF03-NN Near natural EF03    
# 5 EF04-CC Clear cut    EF04    
# 6 EF04-NN Near natural EF04

# Aggregate to bat passes per taxa for night per site
bats_nights_sum <- bats1 %>% group_by(Site, night, taxa) %>% dplyr::summarize(batpass = sum(n())) 
bats_nights_sum1 <- left_join(bats_nights_sum, bat_sitemap)
summary(bats_nights_sum1) #
summary(bats_nights_sum1$batpass)
   # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   # 1.00    2.00    4.00   20.02   14.00  605.00

## Note that the highest number of bat passes in a night that you have is 605, so that should also be the same at the end. 

summary(bats_nights_sum1$Site)
# Number of detector nights per site location before adding zero nights

# EF02-CC EF02-NN EF03-CC EF03-NN EF04-CC EF04-NN EF05-CC EF05-NN 
#      12      31      15      18      47      50      51      62 
# EF06-CC EF06-NN EF07-CC EF07-NN EF08-CC EF08-NN EF09-CC EF09-NN 
#      29      50      31      70      35      57      78      94 
# EF11-CC EF11-NN EF12-CC EF12-NN 
#      34      56      35      45 

# Insert zero activity nights
head(active.nights)

active.nights1 <- active.nights %>% mutate(night = as.Date(DATE.12))
head(active.nights1)

active.nights1$Site <- as.factor(active.nights$SITEPLOT)
active.nights1$night <- as.IDate(active.nights1$night, '%d.%m.%Y')
active.nights1$night <- as.Date(active.nights1$night)
summary(active.nights1)

dat <- bats_nights_sum1 # You had the total number of bat passes per site but I think you should do this for total taxa per site. 
summary(dat)

summary(dat$Site) # Number of nights with recorded bat activity 


#---- ADDING MISSING DAYS 
# Adjust dataset to include nights when detectors were active but no data was collected (zero nights)
head(active.nights)
summary(active.nights$SITEPLOT)

nights <- unique(active.nights1$night) # 48 unique nights of survey 

temp <- expand.grid(Site = unique(dat$Site),  night = nights, taxa = unique(dat$taxa)) #----expanded data

temp$night <-  as.Date(temp$night)
temp <- as.tibble(temp)

active.nights1$Site <- as.factor(active.nights1$Site)
active.nights1$night <-  as.Date(active.nights1$night)
active.nights1 <- as.tibble((active.nights1))

str(temp)
str(active.nights1)

head(temp)
head(active.nights1)

levels(temp$Site)
levels(active.nights1$Site)

## fix the levels of active.nights1 Site 
active.nights2 <- active.nights1 %>% 
  dplyr::mutate(Site = factor(case_when(
    Site == "EF2-CC-B" ~ "EF02-CC", 
    Site == "EF2-NN-B" ~ "EF02-NN", 
    Site == "EF3-CC-B" ~ "EF03-CC", 
    Site == "EF3-NN-B" ~ "EF03-NN",
    Site == "EF4-CC-B" ~ "EF04-CC", 
    Site == "EF4-NN-B" ~ "EF04-NN",
    Site == "EF5-CC-B" ~ "EF05-CC", 
    Site == "EF5-NN-B" ~ "EF05-NN",
    Site == "EF6-CC-B" ~ "EF06-CC", 
    Site == "EF6-NN-B" ~ "EF06-NN",
    Site == "EF7-CC-B" ~ "EF07-CC", 
    Site == "EF7-NN-B" ~ "EF07-NN",
    Site == "EF8-CC-B" ~ "EF08-CC", 
    Site == "EF8-NN-B" ~ "EF08-NN",
    Site == "EF9-CC-B" ~ "EF09-CC", 
    Site == "EF9-NN-B" ~ "EF09-NN",
    Site == "EF11-CC-B" ~ "EF11-CC", 
    Site == "EF11-NN-B" ~ "EF11-NN",
    Site == "EF12-CC-B" ~ "EF12-CC", 
    Site == "EF12-NN-B" ~ "EF12-NN"
  ))) 

levels(bats1$Site)
levels(temp$Site)
levels(active.nights2$Site)

temp2 <- merge(temp, active.nights2) # 6456 obs of 8 variables 

summary(temp2$Site) # number of monitoring nights per per taxa site with zero nights included
### Why have we lost so many nigths for several sites? 

# EF02-CC EF02-NN EF03-CC EF03-NN EF04-CC EF04-NN EF05-CC EF05-NN 
#     232     336     328     328     336     336     328     328 
# EF06-CC EF06-NN EF07-CC EF07-NN EF08-CC EF08-NN EF09-CC EF09-NN 
#     336     336     336     336     344     344     344     344 
# EF11-CC EF11-NN EF12-CC EF12-NN 
#     344     344     160     336 

temp3 <- merge(temp2, dat, all.x = TRUE) 
dim(temp3)
# 6456   11  

#simplify further 
temp4 <- temp3 %>% dplyr::select(-c(SiteType,SitePair, SITEPLOT       , SITETYPE, LOCATION, active.night)) 

summary(temp4) 
# 5556    zero-night-taxa observations 

# reformat factor columns and then replace NA bat passes with zeros 
nbats1 <- temp4 %>% mutate(batpass = replace_na(batpass, 0))

sum(nbats1$batpass)
# 18022 - checks out! 
summary(nbats1$batpass) # max is still 605 - nice! 

## fix the batmap metadata 
bats2 <- left_join(nbats1, bat_sitemap) 
summary(bats2)

##add back the simple manualid column 
taxamap <- bats1 %>% select(manualid, taxa) %>% distinct()
summary(taxamap)
bats3 <- left_join(bats2, taxamap) 

summary(bats3) ## Looks good! 

output_today
#write.csv(bats3, file = file.path(output_today, "Aggregated_pertaxa_pernight.csv"))
#  11.12.2025



```



```{r}
### Visualize 


##unaggregated data
ggplot(bats1, aes(x=DATE.12)) + 
stat_count(geom = "point", aes(y = ..count..), size = 2, color = "orange") +  facet_wrap(~Site, ncol = 5) +
theme_classic() 


## Aggregated by night 
ggplot() +  
  geom_point(data=bats3,aes(x=night,y=Site),size = 4, shape=19,color="grey") + 
  geom_point(data=bats3[bats3$batpass>0,],aes(x=night,y=Site), size = 4, shape=19,color="red") + 
  theme_minimal()


```

